apiVersion: apps/v1
kind: Deployment
metadata:
  name: jiacrontabadmin
spec:
  selector:
    matchLabels:
      app: jiacrontabadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: jiacrontabadmin
    spec:
      imagePullSecrets:
      - name: harborsecret
      containers:
      - name: jiacrontabadmin
        image: 172.16.1.170/base-image/jiacrontab_admin:2.0.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 20000
          name: http
          protocol: TCP
        - containerPort: 20003
          name: rpc
          protocol: TCP
