apiVersion: v1
kind: Service
metadata:
  name: jiacrontabadmin 
  labels:
    app: jiacrontabadmin
spec:
  type: NodePort
  selector:
    app: jiacrontabadmin
  ports:
  - name: http
    protocol: TCP
    port: 20000
  - name: rpc
    protocol: TCP
    port: 20003 
